blueprint:
  name: Motion Detection Lights
  description: "Turn on lights when motion is detected and illuminance is below a specified lux level. Turn off the lights after a specified amount of time of inactivity."
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor to use for the automation
      selector:
        entity:
          domain: binary_sensor
    light:
      name: Lights
      description: The lights that will turn on and off
      selector:
        entity:
          domain: light
    lux_level:
      name: Lux Level
      description: The maximum illuminance level at which the lights should be turned on
      default: 30
      selector:
        number:
          min: 0
          max: 1000
          mode: slider
          step: 1
          unit_of_measurement: lux
    time_period:
      name: Time Period
      description: The amount of time of inactivity after which the lights should be turned off
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    detection_enabled:
      name: Detection enabled switch
      description: The entity that controls if motion detection is in enabled


trigger:
  platform: state
  entity_id: !input motion_sensor
  from: "off"
  to: "on"

condition:
  - condition: numeric_state
    entity_id: sensor.living_room_motion_sensor_illuminance_lux
    below: !input lux_level
  - condition: state
    entity_id: input_boolean.detection_enabled
    state: 'on'

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_sensor
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light

mode: restart
